### ISSUE TITLE
go mod error

### ISSUE THREAD

**Issue by empirefox** [cbednarski/hostess#37]
```bash
go get -u ./...
go: github.com/empirefox/hybrid/pkg/proxy imports
	github.com/cbednarski/hostess imports
	github.com/codegangsta/cli: github.com/codegangsta/cli@v1.22.2: parsing go.mod:
	module declares its path as: github.com/urfave/cli
	        but was required as: github.com/codegangsta/cli
```

**Comment by cbednarski** [comment]
Hi there, I think this is an edge case in `go mod` since I vendored an old version of the `cli` lib and it has since moved on github, via HTTP 301. When you import my project the vendor folder is ignored, and when go get tries to pull github.com/codegangsta/cli it is redirected to urfave instead.

I think in order to fix it I need to re-vendor or repackage the hostess project so the CLI and library components are in different packages.

I'll see if I can fix this over the weekend, but feel free to copy the lib code into your project if you like in the mean time.

**Comment by dgnabasik** [comment]
Any progress on this?
Thanks.

**Comment by cbednarski** [comment]
Hey folks, sorry for the delay but this should be fixed now on master along with some other updates. There are some backwards-incompatible changes on master, notably the library package has moved to `github.com/cbednarski/hostess/hostess` and `github.com/cbednarski/hostess` is the CLI.

I'm going to close this but feel free to open another issue if this is still causing problems for you.

**Comment by empirefox** [comment]
Bump version please.

**Comment by cbednarski** [comment]
Done! 0.4.0 is tagged.

**Comment by parasavelli** [comment]
Hi, I still see the issue while installing on Mac. Any help please ?

$go get -u github.com/Masterminds/glide
go: downloading github.com/Masterminds/glide v0.13.3
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading gopkg.in/yaml.v2 v2.4.0
go: downloading github.com/Masterminds/semver v1.5.0
go: downloading github.com/Masterminds/vcs v1.13.1
go: downloading github.com/codegangsta/cli v1.22.5
go get: github.com/codegangsta/cli@none updating to
	github.com/codegangsta/cli@v1.22.5: parsing go.mod:
	module declares its path as: github.com/urfave/cli
	        but was required as: github.com/codegangsta/cli

**Comment by cbednarski** [comment]
Hi @parasavelli I'm guessing you found this via search, but this project no longer uses `github.com/urfave/cli` or `github.com/codegangsta/cli`. I switched to using the `flag` package in the standard library.

It looks like the [glide](https://github.com/Masterminds/glide) tool you are trying to use is not receiving regular updates these days. If you are looking to use a dependency management tool for Go, I recommend taking a look at the official [`go mod` command](https://blog.golang.org/using-go-modules).

As the error suggests you can find-replace the import paths to fix the issue locally (e.g. `s/github.com\/codegangsta\/cli/github.com\/urfave\/cli/g`):

> module declares its path as: github.com/urfave/cli
> but was required as: github.com/codegangsta/cli
